### ISSUE TITLE
manager-ui: Screen locks if the upstream vPPB is pressed

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl-manager-ui#3]
Crash in FM code when unbinding and binding the device again.
1. `./cxl-util start -c fm -c switch -c sld-group -c host --config-file configs/1vcs_4sld.yaml`
2. Press the upstream vPPB right below the host.
3. The screen locks up.

**Comment by jaekim-fadu** [comment]
Thanks, I fixed it in [f44a19eb8ab6f3d309ba91ff8875db2133397af3](https://github.com/opencxl/opencxl-manager-ui/commit/f44a19eb8ab6f3d309ba91ff8875db2133397af3) commit. Could you check??
