### ISSUE TITLE
manager-ui: CXL switch box smaller than VCS box

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl-manager-ui#4]
When the VCS gets larger, the CXL switch box doesn't scale together. Screenshot below.

![Screenshot from 2024-11-15 19-06-05](https://github.com/user-attachments/assets/f4cc5ab9-7c8f-4bda-b044-fd2e83499653)

**Comment by jaekim-fadu** [comment]
I fixed it in https://github.com/opencxl/opencxl-manager-ui/commit/ce9ba0ee802484c9ce373c91f438e1294b2b1583 commit

* Fixed Page image

<img width="761" alt="image" src="https://github.com/user-attachments/assets/ef3912c6-aafc-4f91-b68e-ea7662e23ff1">
