### ISSUE TITLE
manager-ui: Init screen LD 0 white rather than the color of the bound host

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl-manager-ui#6]
The color of LD 0 of the first MLD device is white rather than the color of the host (blue in this case) on the initial screen.
1. `./cxl-util start -c fm -c switch -c mld-group  -c host-group --config-file configs/1vcs_2mlds.yaml`
2. 
![Screenshot from 2024-11-16 17-01-26](https://github.com/user-attachments/assets/1e2062bc-e30c-401e-b783-f02d7cb1d2f5)

**Comment by jaekim-fadu** [comment]
I fixed it on this commit https://github.com/opencxl/opencxl-manager-ui/commit/9ac2c6a3ebd639e09b8ba81d192a3488925a078c
